#!/bin/bash

if [ $# -eq 0 ]
then
	echo "at least one argument is required"
	exit 1
fi

filename=$1

if [ -f $filename ] || [ -d $filename ]
then
	mv $filename ${filename}.bak
	echo "backup performed on $filename"
fi



