#!/bin/bash
if [[ `xinput --list --short` == *DeathAdder* ]]
then
  xinput --set-prop "Razer Razer DeathAdder" "Device Accel Constant Deceleration" 5
  xinput --set-prop "Razer Razer DeathAdder" "Device Accel Velocity Scaling" 1
fi
xset m 1 0
