#!/bin/bash

## GNOME PolicyKit and Keyring
eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &

## Set root window colour
hsetroot -solid "#2E3436" &

# restore wallpaper
nitrogen --restore &

# trayer, need to run before the others
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
--expand true --width 10 --transparent true --tint 0x000000 --height 16 &

## Volume control for systray
(sleep 2s && pnmixer) &

## Volume keys daemon
xfce4-volumed &

## Enable power management
xfce4-power-manager &

## Start Thunar Daemon
thunar --daemon &

## Detect and configure touchpad. See 'man synclient' for more info.
if egrep -iq 'touchpad' /proc/bus/input/devices; then
    synclient VertEdgeScroll=1 &
    synclient TapButton1=1 &
fi

## Start xscreensaver
xscreensaver -no-splash &

## Start Clipboard manager
(sleep 3s && clipit) &

## Set keyboard settings - 250 ms delay and 25 cps (characters per second) repeat rate.
## Adjust the values according to your preferances.
xset r rate 250 25 &

## Turn on/off system beep
xset b off &

## Run the conky
# conky -q &

# mouse acceleration
xset m 1 0 &

# us keyboard
setxkbmap us &

# ibus daemon
ibus-daemon -rxvd &

# network manager
nm-applet --sm-disable &

# Autostart the Dropbox deamon
(sleep 30s && ~/.dropbox-dist/dropboxd) &

# start xmonad
exec xmonad
